services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: statements
      POSTGRES_PASSWORD: statements
      POSTGRES_DB: statements
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U statements"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: statements
      DB_USER: statements
      DB_PASSWORD: statements
      S3_BUCKET: statements
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      ADMIN_API_KEY: super-secret-key
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  minio-data:
