name: Promote test -> qa

on:
  push:
    branches: [ test ]

permissions:
  contents: write

concurrency:
  group: test-to-qa
  cancel-in-progress: false

jobs:
  build-and-promote:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the commit that triggered this workflow
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run tests
        run: mvn -B -ntp test

      - name: Promote to qa (fast-forward only)
        if: ${{ success() }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Fast-forward qa to this exact commit (rejects if qa diverged)
          git push origin HEAD:refs/heads/qa
